version: '3.7'
services:
  appdb:
    image: mysql:5.7.29
    container_name: app-db
    restart: always
    command: --sql_mode="" #--default-authentication-plugin=mysql_native_password
    ports:
        - '${DB_PORT}:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
        - my-db:/var/lib/mysql
  adminer:
    image: adminer:4.7.6
    container_name: adminer-db
    restart: always
    ports:
      - ${ADMINER_HOST_PORT}:8080
volumes:
    my-db: